#!/bin/bash

##
# Copyright Koninklijke Philips N.V. 2021
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written consent of the copyright owner.
#
# Filename: load-secrets.sh
# Description:
#   Runs inside a devcontainer after start (postStartCommand).
#   Reads Docker secrets from /run/secrets/, exports each as an environment
#   variable (filename uppercased = variable name), and hooks them into
#   ~/.bashrc so every terminal opened in the container has them available.
#
#   This script is generic - it works for any repo that uses Docker secrets
#   via docker-compose.yml. No repo-specific configuration required.
#
# Usage (devcontainer.json postStartCommand):
#   "bash /path/to/repo/external/SGS-Tools/local-build-setup-non-anonymous-artifactory-access/load-secrets.sh"
##

SECRETS_DIR="/run/secrets"
ENV_EXPORTS="${HOME}/.devcontainer-secrets.sh"

if [ ! -d "$SECRETS_DIR" ]; then
    echo "WARNING: $SECRETS_DIR not found; no secrets to load." >&2
    exit 0
fi

# Explicit mapping: secret filename -> env var name
# Anything not listed falls back to the generic UPPERCASE_FILENAME rule.
declare -A SECRET_NAME_MAP
SECRET_NAME_MAP["rt_code_1_user_id"]="RT_USER_ID"

# Build the exports file (overwrite on each container start)
{
    echo "# Auto-generated by load-secrets.sh - do not edit"
    for secret_file in "$SECRETS_DIR"/*; do
        [ -f "$secret_file" ] || continue
        secret_name="$(basename "$secret_file")"
        if [[ -n "${SECRET_NAME_MAP[$secret_name]+_}" ]]; then
            env_var="${SECRET_NAME_MAP[$secret_name]}"
        else
            env_var="$(echo "$secret_name" | tr '[:lower:]' '[:upper:]')"
        fi
        secret_value="$(cat "$secret_file")"
        printf 'export %s="%s"\n' "$env_var" "$secret_value"
    done
} > "$ENV_EXPORTS"

chmod 600 "$ENV_EXPORTS"

source "$ENV_EXPORTS"

# Append hook to ~/.bashrc so every new terminal picks it up
if ! grep -qF "devcontainer-secrets.sh" "${HOME}/.bashrc" 2>/dev/null; then
    echo '[ -f ~/.devcontainer-secrets.sh ] && source ~/.devcontainer-secrets.sh' >> "${HOME}/.bashrc"
fi

echo "Secrets loaded from $SECRETS_DIR into environment."
